package demo;

public class AllStations {

    private static final String EXTENSION = "extension";
    private static final String NORMAL = "normal";
    private static final String LIGHTGREEN = "lightgreen";
    private static final String DARKGREEN = "darkgreen";
    private static final String YELLOW = "yellow";
    private static final String PINK = "pink";
    private static final String BLUE = "blue";
    private static final String ARL = "arl";
    private static final String PURPLE = "purple";

    private AllStations() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }

    public static Station[] getAllStations() {
        return new Station[]{
            new Station("Khu Khot", EXTENSION, "N24", LIGHTGREEN, "BTS"),
            new Station("Yaek Kor Por Aor", EXTENSION, "N23", LIGHTGREEN, "BTS"),
            new Station("Royal Thai Air Force Museum", EXTENSION, "N22", LIGHTGREEN, "BTS"),
            new Station("Bhumibol Adulyadej Hospital", EXTENSION, "N21", LIGHTGREEN, "BTS"),
            new Station("Saphan Mai", EXTENSION, "N20", LIGHTGREEN, "BTS"),
            new Station("Sai Yud", EXTENSION, "N19", LIGHTGREEN, "BTS"),
            new Station("Phahon Yothin 59", EXTENSION, "N18", LIGHTGREEN, "BTS"),
            new Station("Wat Phra Sri Mahathat", EXTENSION, "N17", LIGHTGREEN, "BTS"),
            new Station("11th Infantry Regiment", EXTENSION, "N16", LIGHTGREEN, "BTS"),
            new Station("Bang Bua", EXTENSION, "N15", LIGHTGREEN, "BTS"),
            new Station("Royal Forest Department", EXTENSION, "N14", LIGHTGREEN, "BTS"),
            new Station("Kasetsart University", EXTENSION, "N13", LIGHTGREEN, "BTS"),
            new Station("Sena Nikhom", EXTENSION, "N12", LIGHTGREEN, "BTS"),
            new Station("Ratchayothin", EXTENSION, "N11", LIGHTGREEN, "BTS"),
            new Station("Phahon Yothin 24", EXTENSION, "N10", LIGHTGREEN, "BTS"),
            new Station("Ha Yaek Lat Phrao", EXTENSION, "N9", LIGHTGREEN, "BTS"),
            new Station("Mo Chit", NORMAL, "N8", LIGHTGREEN, "BTS"),
            new Station("Saphan Khwai", NORMAL, "N7", LIGHTGREEN, "BTS"),
            new Station("Sena Ruam", NORMAL, "N6", LIGHTGREEN, "BTS"),
            new Station("Ari", NORMAL, "N5", LIGHTGREEN, "BTS"),
            new Station("Sanam Pao", NORMAL, "N4", LIGHTGREEN, "BTS"),
            new Station("Victory Monument", NORMAL, "N3", LIGHTGREEN, "BTS"),
            new Station("Phaya Thai", NORMAL, "N2", LIGHTGREEN, "BTS"),
            new Station("Ratchathewi", NORMAL, "N1", LIGHTGREEN, "BTS"),
            new Station("Siam", NORMAL, "CEN", LIGHTGREEN, "BTS"),
            new Station("Chit Lom", NORMAL, "E1", LIGHTGREEN, "BTS"),
            new Station("Phloen Chit", NORMAL, "E2", LIGHTGREEN, "BTS"),
            new Station("Nana", NORMAL, "E3", LIGHTGREEN, "BTS"),
            new Station("Asok", NORMAL, "E4", LIGHTGREEN, "BTS"),
            new Station("Phrom Phong", NORMAL, "E5", LIGHTGREEN, "BTS"),
            new Station("Thong Lo", NORMAL, "E6", LIGHTGREEN, "BTS"),
            new Station("Ekkamai", NORMAL, "E7", LIGHTGREEN, "BTS"),
            new Station("Phra Khanong", NORMAL, "E8", LIGHTGREEN, "BTS"),
            new Station("On Nut", NORMAL, "E9", LIGHTGREEN, "BTS"),
            new Station("Bang Chak", EXTENSION, "E10", LIGHTGREEN, "BTS"),
            new Station("Punnawithi", EXTENSION, "E11", LIGHTGREEN, "BTS"),
            new Station("Udom Suk", EXTENSION, "E12", LIGHTGREEN, "BTS"),
            new Station("Bang Na", EXTENSION, "E13", LIGHTGREEN, "BTS"),
            new Station("Bearing", EXTENSION, "E14", LIGHTGREEN, "BTS"),
            new Station("Samrong", EXTENSION, "E15", LIGHTGREEN, "BTS"),
            new Station("Pu Chao", EXTENSION, "E16", LIGHTGREEN, "BTS"),
            new Station("Chang Erawan", EXTENSION, "E17", LIGHTGREEN, "BTS"),
            new Station("Royal Thai Naval Academy", EXTENSION, "E18", LIGHTGREEN, "BTS"),
            new Station("Pak Nam", EXTENSION, "E19", LIGHTGREEN, "BTS"),
            new Station("Srinagarindra", EXTENSION, "E20", LIGHTGREEN, "BTS"),
            new Station("Phraek Sa", EXTENSION, "E21", LIGHTGREEN, "BTS"),
            new Station("Sai Luat", EXTENSION, "E22", LIGHTGREEN, "BTS"),
            new Station("Kheha", EXTENSION, "E23", LIGHTGREEN, "BTS"),

            // Dark Green Line
            new Station("National Stadium", NORMAL, "W1", DARKGREEN, "BTS"),
            new Station("Siam", NORMAL, "CEN", DARKGREEN, "BTS"),
            new Station("Ratchadamri", NORMAL, "S1", DARKGREEN, "BTS"),
            new Station("Sala Daeng", NORMAL, "S2", DARKGREEN, "BTS"),
            new Station("Chong Nonsi", NORMAL, "S3", DARKGREEN, "BTS"),
            new Station("Saint Louis", NORMAL, "S4", DARKGREEN, "BTS"),
            new Station("Surasak", NORMAL, "S5", DARKGREEN, "BTS"),
            new Station("Saphan Taksin", NORMAL, "S6", DARKGREEN, "BTS"),
            new Station("Krung Thon Buri", NORMAL, "S7", DARKGREEN, "BTS"),
            new Station("Wongwian Yai", NORMAL, "S8", DARKGREEN, "BTS"),
            new Station("Pho Nimit", EXTENSION, "S9", DARKGREEN, "BTS"),
            new Station("Talat Phlu", EXTENSION, "S10", DARKGREEN, "BTS"),
            new Station("Wutthakat", EXTENSION, "S11", DARKGREEN, "BTS"),
            new Station("Bang Wa", EXTENSION, "S12", DARKGREEN, "BTS"),

            // Gold Line
            new Station("Krung Thon Buri", NORMAL, "G1", "gold", "BTS"),
            new Station("Chareon Nakhon", NORMAL, "G2", "gold", "BTS"),
            new Station("Khlong San", NORMAL, "G3", "gold", "BTS"),

            // Yellow Line
            new Station("Lat Phrao", NORMAL, "YL01", YELLOW, "BTS"),
            new Station("Phawana", NORMAL, "YL02", YELLOW, "BTS"),
            new Station("Chok Chai 4", NORMAL, "YL03", YELLOW, "BTS"),
            new Station("Lat Phrao 71", NORMAL, "YL04", YELLOW, "BTS"),
            new Station("Lat Phrao 83", NORMAL, "YL05", YELLOW, "BTS"),
            new Station("Mahadthai", NORMAL, "YL06", YELLOW, "BTS"),
            new Station("Lat Phrao 101", NORMAL, "YL07", YELLOW, "BTS"),
            new Station("Bang Kapi", NORMAL, "YL08", YELLOW, "BTS"),
            new Station("Yeak Lam Sali", NORMAL, "YL09", YELLOW, "BTS"),
            new Station("Si Kritha", NORMAL, "YL10", YELLOW, "BTS"),
            new Station("Hua Mak", NORMAL, "YL11", YELLOW, "BTS"),
            new Station("Kelantan", NORMAL, "YL12", YELLOW, "BTS"),
            new Station("Si Nut", NORMAL, "YL13", YELLOW, "BTS"),
            new Station("Srinagarindra 38", NORMAL, "YL14", YELLOW, "BTS"),
            new Station("Suan Luang Rama IX", NORMAL, "YL15", YELLOW, "BTS"),
            new Station("Si Udom", NORMAL, "YL16", YELLOW, "BTS"),
            new Station("Si Iam", NORMAL, "YL17", YELLOW, "BTS"),
            new Station("Si La Salle", NORMAL, "YL18", YELLOW, "BTS"),
            new Station("Si Bearing", NORMAL, "YL19", YELLOW, "BTS"),
            new Station("Si Dan", NORMAL, "YL20", YELLOW, "BTS"),
            new Station("Si Thepha", NORMAL, "YL21", YELLOW, "BTS"),
            new Station("Thipphawan", NORMAL, "YL22", YELLOW, "BTS"),
            new Station("Samrong", NORMAL, "YL23", YELLOW, "BTS"),

            // Pink Line
            new Station("Nonthaburi Civic Center", NORMAL, "PK01", PINK, "BTS"),
            new Station("Khae Rai", NORMAL, "PK02", PINK, "BTS"),
            new Station("Sanambin Nam", NORMAL, "PK03", PINK, "BTS"),
            new Station("Samakkhi", NORMAL, "PK04", PINK, "BTS"),
            new Station("Royal Irrigation Department", NORMAL, "PK05", PINK, "BTS"),
            new Station("Yeak Pak Kret", NORMAL, "PK06", PINK, "BTS"),
            new Station("Pak Kret Bypass", NORMAL, "PK07", PINK, "BTS"),
            new Station("Chaeng Watthana-Pak Kret 28", NORMAL, "PK08", PINK, "BTS"),
            new Station("Si Rat", NORMAL, "PK09", PINK, "BTS"),
            new Station("Muang Thong Thani", NORMAL, "PK10", PINK, "BTS"),
            new Station("Chaeng Watthana 14", NORMAL, "PK11", PINK, "BTS"),
            new Station("Goverment Complex", NORMAL, "PK12", PINK, "BTS"),
            new Station("National Telecom", NORMAL, "PK13", PINK, "BTS"),
            new Station("Lak Si", NORMAL, "PK14", PINK, "BTS"),
            new Station("Rajabhat Phranakhon", NORMAL, "PK15", PINK, "BTS"),
            new Station("Wat Phra Sri Mahathat", NORMAL, "PK16", PINK, "BTS"),
            new Station("Ram Inthra 3", NORMAL, "PK17", PINK, "BTS"),
            new Station("Lat Pla Khao", NORMAL, "PK18", PINK, "BTS"),
            new Station("Ram Inthra Kor Mor 4", NORMAL, "PK19", PINK, "BTS"),
            new Station("Maiyalap", NORMAL, "PK20", PINK, "BTS"),
            new Station("Vacharaphol", NORMAL, "PK21", PINK, "BTS"),
            new Station("Khu Bon", NORMAL, "PK23", PINK, "BTS"),
            new Station("Ram Inthra Kor Mor 9", NORMAL, "PK24", PINK, "BTS"),
            new Station("Outer Ring Road-Ram Inthra", NORMAL, "PK25", PINK, "BTS"),
            new Station("Nopparat", NORMAL, "PK26", PINK, "BTS"),
            new Station("Bang Chan", NORMAL, "PK27", PINK, "BTS"),
            new Station("Setthabutbamphen", NORMAL, "PK28", PINK, "BTS"),
            new Station("Min Buri Market", NORMAL, "PK29", PINK, "BTS"),
            new Station("Min Buri", NORMAL, "PK30", PINK, "BTS"),

            // Blue Line
            new Station("Tha Phra", NORMAL, "BL01", BLUE, "MRT"),
            new Station("Charan 13", NORMAL, "BL02", BLUE, "MRT"),
            new Station("Fai Chai", NORMAL, "BL03", BLUE, "MRT"),
            new Station("Bang Khun Non", NORMAL, "BL04", BLUE, "MRT"),
            new Station("Bang Yi Khan", NORMAL, "BL05", BLUE, "MRT"),
            new Station("Sirindhorn", NORMAL, "BL06", BLUE, "MRT"),
            new Station("Bang Phlat", NORMAL, "BL07", BLUE, "MRT"),
            new Station("Bang O", NORMAL, "BL08", BLUE, "MRT"),
            new Station("Bang Pho", NORMAL, "BL09", BLUE, "MRT"),
            new Station("Tao Poon", NORMAL, "BL10", BLUE, "MRT"),
            new Station("Bang Sue", NORMAL, "BL11", BLUE, "MRT"),
            new Station("Kamphaeng Phet", NORMAL, "BL12", BLUE, "MRT"),
            new Station("Chatuchak Park", NORMAL, "BL13", BLUE, "MRT"),
            new Station("Phahon Yothin", NORMAL, "BL14", BLUE, "MRT"),
            new Station("Lat Phrao", NORMAL, "BL15", BLUE, "MRT"),
            new Station("Ratchadaphisek", NORMAL, "BL16", BLUE, "MRT"),
            new Station("Sutthisan", NORMAL, "BL17", BLUE, "MRT"),
            new Station("Huai Khwang", NORMAL, "BL18", BLUE, "MRT"),
            new Station("Thailand Cultural Centre", NORMAL, "BL19", BLUE, "MRT"),
            new Station("Phra Ram 9", NORMAL, "BL20", BLUE, "MRT"),
            new Station("Phetchaburi", NORMAL, "BL21", BLUE, "MRT"),
            new Station("Sukhumvit", NORMAL, "BL22", BLUE, "MRT"),
            new Station("Queen Sirikit National Convention Centre", NORMAL, "BL23", BLUE, "MRT"),
            new Station("Khlong Toei", NORMAL, "BL24", BLUE, "MRT"),
            new Station("Lumphini", NORMAL, "BL25", BLUE, "MRT"),
            new Station("Si Lom", NORMAL, "BL26", BLUE, "MRT"),
            new Station("Sam Yan", NORMAL, "BL27", BLUE, "MRT"),
            new Station("Hua Lamphong", NORMAL, "BL28", BLUE, "MRT"),
            new Station("Wat Mangkon", NORMAL, "BL29", BLUE, "MRT"),
            new Station("Sam Yot", NORMAL, "BL30", BLUE, "MRT"),
            new Station("Sanam Chai", NORMAL, "BL31", BLUE, "MRT"),
            new Station("Itsaraphap", NORMAL, "BL32", BLUE, "MRT"),
            new Station("Bang Phai", NORMAL, "BL33", BLUE, "MRT"),
            new Station("Bang Wa", NORMAL, "BL34", BLUE, "MRT"),
            new Station("Phetkasem 48", NORMAL, "BL35", BLUE, "MRT"),
            new Station("Phasi Charoen", NORMAL, "BL36", BLUE, "MRT"),
            new Station("Bang Khae", NORMAL, "BL37", BLUE, "MRT"),
            new Station("Lak Song", NORMAL, "BL38", BLUE, "MRT"),

            // Airport Rail Link
            new Station("Phaya Thai", NORMAL, "A1", ARL, "SRT"),
            new Station("Ratchaprarop", NORMAL, "A2", ARL, "SRT"),
            new Station("Makkasan", NORMAL, "A3", ARL, "SRT"),
            new Station("Ramkhamhaeng", NORMAL, "A4", ARL, "SRT"),
            new Station("Hua Mak", NORMAL, "A5", ARL, "SRT"),
            new Station("Ban Thap Chang", NORMAL, "A6", ARL, "SRT"),
            new Station("Lat Krabang", NORMAL, "A7", ARL, "SRT"),
            new Station("Suvarnabhumi", NORMAL, "A8", ARL, "SRT"),

            // Purple Line
            new Station("Khlong Bang Phai", NORMAL, "PP01", PURPLE, "MRT"),
            new Station("Talad Bang Yai", NORMAL, "PP02", PURPLE, "MRT"),
            new Station("Sam Yaek Bang Yai", NORMAL, "PP03", PURPLE, "MRT"),
            new Station("Bang Phlu", NORMAL, "PP04", PURPLE, "MRT"),
            new Station("Bang Rak Yai", NORMAL, "PP05", PURPLE, "MRT"),
            new Station("Bang Rak Noi Tha It", NORMAL, "PP06", PURPLE, "MRT"),
            new Station("Sai Ma", NORMAL, "PP07", PURPLE, "MRT"),
            new Station("Phra Nang Klao Bridge", NORMAL, "PP08", PURPLE, "MRT"),
            new Station("Yaek Nonthaburi 1", NORMAL, "PP09", PURPLE, "MRT"),
            new Station("Bang Krasor", NORMAL, "PP10", PURPLE, "MRT"),
            new Station("Nonthaburi Civic Center", NORMAL, "PP11", PURPLE, "MRT"),
            new Station("Ministry of Public Health", NORMAL, "PP12", PURPLE, "MRT"),
            new Station("Yaek Tiwanon", NORMAL, "PP13", PURPLE, "MRT"),
            new Station("Wong Sawang", NORMAL, "PP14", PURPLE, "MRT"),
            new Station("Bang Son", NORMAL, "PP15", PURPLE, "MRT"),
            new Station("Tao Poon", NORMAL, "PP16", PURPLE, "MRT")
        };
    }
}
